export const DELETE_TRANSACTION = "DELETE_TRANSACTION"
export const CREATE_TRANSACTION = "CREATE_TRANSACTION"
export const REFRESH_TRANSACTION = "REFRESH_TRANSACTION"
export const LOAD_TRANSACTION = "LOAD_TRANSACTION"